// <auto-generated />
namespace FIT5032_main_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddchnagesToPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddchnagesToPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202309281240062_AddchnagesToPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
